CREATE DATABASE IF NOT EXISTS CyberBunker;
USE CyberBunker;
CREATE TABLE USERS(
FIRST_NAME VARCHAR (500) NOT NULL,
LAST_NAME VARCHAR(500) NOT NULL,
EAMIL VARCHAR (500) NOT NULL,
PASWORD VARCHAR(500) NOT NULL
);

INSERT INTO USERS(FIRST_NAME,LAST_NAME,EAMIL,PASWORD)
VALUE ('HASSAN','MARWAN' ,'HASSAN@GMAIL.COM', 1234);
SELECT *
FROM USERS;
